version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:15
    container_name: cities_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-cities_db}
    volumes:
      - cities_postgres_data:/var/lib/postgresql/data
      - ./db/init/init_cities_db.sql:/docker-entrypoint-initdb.d/init_cities_db.sql
      - ./db/data:/docker-entrypoint-initdb.d/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-cities_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  cities_postgres_data: 